# -*- coding: utf-8 -*-
"""data-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ym-VObaY-7tb-xdH-aM4BexclAzmzvmw
"""

!pip install seaborn
!pip install  scikit-learn

import json
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
from sklearn.preprocessing import StandardScaler

def load_data(directory):
    data = []
    print( os.listdir(directory))
    files = glob.glob(directory + '/**/*.json', recursive=True)
    for filename in files:

        if "obj.json" in filename:
            with open(filename, 'r') as file:
                data.append(json.load(file))
    return data



import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def plot_distribution(data, title, y_label, x_label,  kde=True):
    color = np.random.choice(["blue", "green", "purple", "orange", "brown", "pink", "red", "yellow"])
    sns.histplot(data, kde=kde, color=color)
    plt.title(title)
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.show()


def plot_shapes_distribution(shapes):
    df_shapes = pd.DataFrame({"shape": shapes})
    plt.figure(figsize=(8, 6))
    sns.countplot(x="shape", data=df_shapes, palette="viridis")
    plt.title("Distribution of Shapes")
    plt.xlabel("Shape")
    plt.ylabel("Count")
    plt.show()

def extract_world_features(data):
    # floor
    friction_static = []
    friction_dynamic = []
    friction_spin = []
    # floor_rgba_r = []
    # floor_rgba_g = []
    # floor_rgba_b = []
    floor_speculars = []
    floor_shininesses = []

    # camera
    camera_lookat_x = []
    camera_lookat_y = []
    camera_lookat_z = []
    camera_distance = []
    camera_azimuth = []
    camera_elevation = []

    # lights
    lights_pos_x = []
    lights_pos_y = []
    lights_pos_z = []
    lights_diffuse_r = []
    lights_diffuse_g = []
    lights_diffuse_b = []
    lights_specular_r = []
    lights_specular_g = []
    lights_specular_b = []
    lights_cutoff = []
    lights_directional = []

    for item in data:
        world = item.get("world", {})
        floor = world.get("floor", {})
        camera = world.get("camera", {})
        lights = world.get("lights", [])

        # floor friction
        friction_str = floor.get("friction", "0 0 0")
        frictions = friction_str.split()
        friction_static.append(float(frictions[0]))
        friction_dynamic.append(float(frictions[1]))
        friction_spin.append(float(frictions[2]))

        # rgba_str = floor.get("rgba", "0 0 0 1")
        # rgba = [float(c) for c in rgba_str.split()]
        # floor_rgba_r.append(rgba[0])
        # floor_rgba_g.append(rgba[1])
        # floor_rgba_b.append(rgba[2])

        # specular and shininess
        floor_speculars.append(float(floor.get("specular", 0)))
        floor_shininesses.append(float(floor.get("shininess", 0)))


        lookat = camera.get("lookat", [0, 0, 0])
        camera_lookat_x.append(float(lookat[0]) if len(lookat) > 0 else 0)
        camera_lookat_y.append(float(lookat[1]) if len(lookat) > 1 else 0)
        camera_lookat_z.append(float(lookat[2]) if len(lookat) > 2 else 0)
        camera_distance.append(float(camera.get("distance", 0)))
        camera_azimuth.append(float(camera.get("azimuth", 0)))
        camera_elevation.append(float(camera.get("elevation", 0)))

        for light in lights:
            pos = light.get("pos", [0, 0, 0])
            lights_pos_x.append(float(pos[0]) if len(pos) > 0 else 0)
            lights_pos_y.append(float(pos[1]) if len(pos) > 1 else 0)
            lights_pos_z.append(float(pos[2]) if len(pos) > 2 else 0)

            diffuse_str = light.get("diffuse", "0 0 0")
            diffuse = [float(c) for c in diffuse_str.split()]
            lights_diffuse_r.append(diffuse[0] if len(diffuse) > 0 else 0)
            lights_diffuse_g.append(diffuse[1] if len(diffuse) > 1 else 0)
            lights_diffuse_b.append(diffuse[2] if len(diffuse) > 2 else 0)

            # specular_str = light.get("specular", "0 0 0")
            # specular = [float(c) for c in specular_str.split()]
            # lights_specular_r.append(specular[0] if len(specular) > 0 else 0)
            # lights_specular_g.append(specular[1] if len(specular) > 1 else 0)
            # lights_specular_b.append(specular[2] if len(specular) > 2 else 0)

            lights_cutoff.append(float(light.get("cutoff", 0)))
            # lights_directional.append(bool(light.get("directional", False)))


    return {
        "friction_static": friction_static,
        "friction_dynamic": friction_dynamic,
        "friction_spin": friction_spin,
        # "floor_rgba_r": floor_rgba_r,
        # "floor_rgba_g": floor_rgba_g,
        # "floor_rgba_b": floor_rgba_b,
        "floor_speculars": floor_speculars,
        "floor_shininesses": floor_shininesses,

        "camera_lookat_x": camera_lookat_x,
        "camera_lookat_y": camera_lookat_y,
        "camera_lookat_z": camera_lookat_z,
        "camera_distance": camera_distance,
        "camera_azimuth": camera_azimuth,
        "camera_elevation": camera_elevation,

        "lights_pos_x": lights_pos_x,
        "lights_pos_y": lights_pos_y,
        "lights_pos_z": lights_pos_z,
        # "lights_diffuse_r": lights_diffuse_r,
        # "lights_diffuse_g": lights_diffuse_g,
        # "lights_diffuse_b": lights_diffuse_b,
        # "lights_specular_r": lights_specular_r,
        # "lights_specular_g": lights_specular_g,
        # "lights_specular_b": lights_specular_b,
        "lights_cutoff": lights_cutoff,
    }



def extract_features(data):
    masses = []
    velocities = []
    accelerations = []
    angular_velocities = []
    angular_accelerations = []
    frictions = []
    friction_static = []
    friction_dynamic = []
    friction_spin = []
    densities = []
    elasticities = []
    shapes = []

    prev_info = {}

    for item in data:
        objects = item.get("objects", [])

        frames = item.get("frames", [])
        for frame in frames:
            time_current = frame['time']

            for obj_id, obj in frame['objects'].items():
                #  current velocity magnitude
                current_velocity = np.linalg.norm(obj.get('velocity', []))
                velocities.append(current_velocity)
                # current angular velocity magnitude
                current_ang_vel = np.linalg.norm(obj.get('angular_velocity', []))
                angular_velocities.append(current_ang_vel)

                #  acceleration if previous data exists for this object
                if obj_id in prev_info:
                    prev_time, prev_vel, prev_ang_vel = prev_info[obj_id]
                    dt = time_current - prev_time
                    # if dt > 0:
                    if current_velocity >  np.linalg.norm(prev_vel):
                        acc = np.linalg.norm((current_velocity - prev_vel) / dt)
                        ang_acc = np.linalg.norm((current_ang_vel - prev_ang_vel) / dt)
                        accelerations.append(acc)
                        angular_accelerations.append(ang_acc)
                # Update previous info for this object
                prev_info[obj_id] = (time_current, current_velocity, current_ang_vel)

            for obj in objects:
                masses.append(obj.get('mass'))

                friction_str = obj.get("friction", "0 0 0")
                frictions = friction_str.split(' ')
                friction_static.append(float(frictions[0]))
                friction_dynamic.append(float(frictions[1]))
                friction_spin.append(float(frictions[2]))

                densities.append(obj.get('density'))
                elasticities.append(obj.get('elasticity'))
                shapes.append(obj.get('shape'))


    return {
        "masses": masses,
        "velocities": velocities,
        "accelerations": accelerations,
        "angular_velocities": angular_velocities,
        "angular_accelerations": angular_accelerations,
        "friction_static": friction_static,
        "friction_dynamic": friction_dynamic,
        "friction_spin": friction_spin,
        "densities": densities,
        "elasticities": elasticities,
        "shapes": shapes,
    }
    # return (masses, velocities, accelerations, angular_velocities,
    #         angular_accelerations, frictions, densities, elasticities)

directory = 'generated'
data = load_data(directory)
# datas

# masses, velocities, accelerations, frictions, densities, elasticities = extract_features(data)

"""### Floor friction"""

world_features = extract_world_features(data)

plot_distribution(world_features["friction_static"], "Floor Static Friction Distribution", "Frequency", " Static Friction")
plot_distribution(world_features["friction_dynamic"], "Floor Dynamic Friction Distribution", "Frequency", " Dynamic Friction")
plot_distribution(world_features["friction_spin"], "Floor Spin Friction Distribution", "Frequency", " Spin Friction")

plot_distribution(world_features["floor_speculars"], "Floor Specular Distribution", "Frequency", "Specular")
plot_distribution(world_features["floor_shininesses"], "Floor Shininess Distribution", "Frequency", "Shininess")

"""### Camera"""

plot_distribution(world_features["camera_distance"], "Camera Distance Distribution", "Frequency", "Distance")
plot_distribution(world_features["camera_azimuth"], "Camera Azimuth Distribution", "Frequency", "Azimuth")
plot_distribution(world_features["camera_elevation"], "Camera Elevation Distribution", "Frequency", "Elevation")

"""### Lights"""

plot_distribution(world_features["lights_pos_x"], "Lights Position X Distribution", "Frequency", "X Position")
plot_distribution(world_features["lights_pos_y"], "Lights Position Y Distribution", "Frequency", "Y Position")
plot_distribution(world_features["lights_pos_z"], "Lights Position Z Distribution", "Frequency", "Z Position")
# plot_distribution(world_features["lights_diffuse_r"], "Lights Diffuse Red Distribution", "Frequency", "Diffuse R")
# plot_distribution(world_features["lights_diffuse_g"], "Lights Diffuse Green Distribution", "Frequency", "Diffuse G")
# plot_distribution(world_features["lights_diffuse_b"], "Lights Diffuse Blue Distribution", "Frequency", "Diffuse B")
# plot_distribution(world_features["lights_specular_r"], "Lights Specular Red Distribution", "Frequency", "Specular R")
# plot_distribution(world_features["lights_specular_g"], "Lights Specular Green Distribution", "Frequency", "Specular G")
# plot_distribution(world_features["lights_specular_b"], "Lights Specular Blue Distribution", "Frequency", "Specular B")
plot_distribution(world_features["lights_cutoff"], "Lights Cutoff Distribution", "Frequency", "Cutoff")
# plot_distribution(world_features["lights_directional"], "Lights Directional Distribution", "Frequency", "Directional")



"""### Elements"""

extracted_data = extract_features(data)
masses = extracted_data["masses"]
velocities = extracted_data["velocities"]
accelerations = extracted_data["accelerations"]
angular_velocities = extracted_data["angular_velocities"]

friction_static = extracted_data["friction_static"]
friction_dynamic = extracted_data["friction_dynamic"]
friction_spin = extracted_data["friction_spin"]

# frictions = extracted_data["frictions"]
densities = extracted_data["densities"]
elasticities = extracted_data["elasticities"]

shapes = extracted_data["shapes"]

# len(masses), len(velocities), len(accelerations), len(frictions), len(elasticities)

# plt.subplot(1, 2, 1)
plot_distribution(masses, "Mass", "Frequency", "Mass")
# plt.subplot(1, 2, 2)
# plt.tight_layout()
plot_distribution(friction_static, "friction_static", "Frequency", "frictions")
plot_distribution(friction_dynamic, "friction_dynamic", "Frequency", "frictions")
plot_distribution(friction_spin, "friction_spin", "Frequency", "frictions")
plot_distribution(densities, "densities", "Frequency", "densities")
plot_distribution(elasticities, "elasticities", "Frequency", "elasticities")
plot_shapes_distribution(shapes)

velocities_1 = list(filter(lambda v: round(v, 3) > 0, velocities))

plot_distribution(velocities_1, "velocities", "Frequency", "velocities")
# plot_distribution(accelerations, "accelerations", "Frequency", "accelerations", kde=False)

filtered_accelerations = [a for a in accelerations if  round(a, 3) > 0]
print(len(accelerations), len(filtered_accelerations))


plt.hist(filtered_accelerations, bins=100)
plt.title("Acceleration Distribution")
plt.xlabel("Acceleration")
plt.ylabel("Frequency")
plt.show()

def analyze_data(extracted_features, use_correlation=False, scale_data=False):
    # extracted_features = extract_features(input_data)

    data = {k: v for k, v in extracted_features.items() if v}
    # print(data)
    max_length = max(len(data[key]) for key in data)
    # print("max_length", max_length)
    # Pad shorter lists with NaN to match the maximum length
    for key in data:
        # print("key", key)
        # print(len(data[key]))
        # print(data[key][-10:])
        if len(data[key]) < max_length:
            # print(len(data[key]))
            # data[key].extend(data[key] * (max_length - len(data[key])))
            while len(data[key]) < max_length:
                data[key].append(np.nan)


    df = pd.DataFrame(data)
    df = df.dropna()

    if scale_data:
        scaler = StandardScaler()
        df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns) # Scale data

    if use_correlation:
        matrix = df.corr(method='pearson')
        title = 'Correlation Matrix of Physical Properties'
    else:
        matrix = df.cov()
        title = 'Covariance Matrix of Physical Properties'

    plt.figure(figsize=(12, 10))
    sns.heatmap(matrix, annot=True, cmap='coolwarm', fmt=".2f")
    plt.title(title)
    plt.show()

obj_features = extract_features(data)
del obj_features["shapes"]
world_features = extract_world_features(data)
analyze_data(obj_features, use_correlation=True, scale_data=True)
# analyze_data(world_features, use_correlation=True, scale_data=True)

obj_features = extract_features(data)
analyze_data(obj_features, use_correlation=False, scale_data=True)

"""### Video analysis"""

directory = 'generated'
data = load_data(directory)

df = data[5]
frames = df.get("frames", {})
objects = df.get("objects", {})

object_ids = list(frames[0]["objects"].keys())
object_ids

velocities = {obj_id: [] for obj_id in object_ids}

for frame in frames:
    for obj_id in object_ids:
        vel = frame["objects"].get(obj_id, {}).get("velocity", [0, 0, 0])
        velocities[obj_id].append(np.linalg.norm(vel))


velocity_df = pd.DataFrame(velocities)
velocity_df

matrix = velocity_df.corr(method='pearson')
title = 'Correlation Matrix of velocities'

plt.figure(figsize=(12, 10))
sns.heatmap(matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title(title)
plt.show()

""" Strong positive correlation can point out that elements are being influenced by the same factors - friction, collisions.

 Negative correlation can indicate that it's moving in opposite direction or influenced by different factors.

"""

df_objects = pd.DataFrame(objects)
# df_objects.iloc[0, :]
# object_ids

df_combined = velocity_df.melt(var_name="id", value_name="velocity")
df_combined = df_combined.merge(df_objects, on="id")

df_combined.head()

df_combined.iloc[0,:]

# velocity vs mass
plt.figure(figsize=(8, 6))
sns.scatterplot(x="mass", y="velocity_x", hue="material", data=df_combined, s=100)
plt.title("Velocity vs. Mass (Colored by Material)")
plt.xlabel("Mass (kg)")
plt.ylabel("Velocity Magnitude")
plt.show()

"""Heavier objects may have lower velocity due to friction and inertia

"""

df_combined["avg_friction"] = df_combined["friction"][0].apply(lambda f: np.mean(float(f)))

df_combined

# average friction
df_combined["avg_friction"] = df_combined["friction"].apply(lambda f: np.mean(f))

# Plot velocity vs. average friction
plt.figure(figsize=(8, 6))
sns.scatterplot(x="avg_friction", y="velocity_x", hue="material", data=df_combined, s=100)
plt.title("Velocity vs. Average Friction (Colored by Material)")
plt.xlabel("Average Friction")
plt.ylabel("Velocity Magnitude")
plt.show()



# # velocity dist shape
# plt.figure(figsize=(8, 6))
# sns.boxplot(x="shape", y="velocity_x", data=df_combined)
# sns.violinplot(x="shape", y="velocity_x", data=df_combined)
# plt.title("Velocity Distribution by Shape")
# plt.xlabel("Shape")
# plt.ylabel("Velocity Magnitude")
# plt.show()



plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
sns.boxplot(x="shape", y="velocity_x", data=df_combined)
plt.title("Velocity Distribution by Shape")
plt.xlabel("Shape")
plt.ylabel("Velocity Magnitude")

plt.subplot(1, 2, 2)
sns.violinplot(x="shape", y="velocity_x", data=df_combined)
plt.title("Velocity Distribution by Shape")
plt.xlabel("Shape")
plt.ylabel("Velocity Magnitude")

plt.tight_layout()
plt.show()

collision_counts = {obj_id: 0 for obj_id in object_ids}

for frame in frames:
    for obj_id in object_ids:
        taxonomy = frame["objects"].get(obj_id, {}).get("taxonomy", [])
        for event in taxonomy:
            if event.get("category") == "Interaction Events" and event.get("subcategory") == "Collisions":
                collision_counts[obj_id] += 1

collision_df = pd.DataFrame(list(collision_counts.items()), columns=["id", "collision_count"])
collision_df

average_velocity = velocity_df.mean().reset_index()
average_velocity.columns = ["id", "average_velocity"]

df_analysis = average_velocity.merge(collision_df, on="id")
df_analysis["num_objects"] = len(object_ids)
df_analysis

plt.figure(figsize=(8, 6))
sns.scatterplot(x="collision_count", y="average_velocity", data=df_analysis, hue="id")
plt.title("Avg Velocity vs. Number of Collisions")
plt.xlabel("Number of Collisions")
plt.ylabel("Avg Velocity")
plt.show()

from scipy.stats import pearsonr


corr, p_value = pearsonr(df_analysis["collision_count"], df_analysis["average_velocity"])
print(f"Velocity vs collision count: {corr:.2f}, P-value: {p_value:.4f}")

df_analysis

velocity_stats = velocity_df.agg(["mean", "std", "min", "max"]).T.reset_index()
velocity_stats.columns = ["id", "mean_velocity", "std_velocity", "min_velocity", "max_velocity"]

df_analysis = velocity_stats.merge(collision_df, on="id")
df_analysis

plt.figure(figsize=(8, 6))
sns.histplot(df_analysis["collision_count"], bins=10, kde=True)
plt.title("Dist collision freq")
plt.xlabel("Number of Collisions")
plt.ylabel("Frequency")
plt.show()

sns.histplot(df_analysis["mean_velocity"], bins=10, kde=True)
plt.title("Dist avg velocity")
plt.xlabel("avg velocity")
plt.ylabel("Frequency")
plt.show()

sns.scatterplot(x="collision_count", y="std_velocity", data=df_analysis, hue="id")
plt.title("Collision  vs velocity stability")
plt.xlabel("Number of Collisions")
plt.ylabel("Velocity Standard Deviation (Stability)")
plt.show()

corr, p_value = pearsonr(df_analysis["collision_count"], df_analysis["std_velocity"])
print(f"correlation xollisions vs vel stability: {corr:.2f}, P-value: {p_value:.4f}")

