[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phlop"
version = "0.1.0"
description = "PHLOP project"
authors = [{name = ""}]
dependencies = [
    "mujoco",
    "mujoco-py",
    "numpy",
    "opencv-python",
    "matplotlib",
    "scipy",
    "glfw",
    "imageio",
    "imageio[ffmpeg]",
    "pyopengl",
    "tqdm",
    "ruff",
    "pyarrow",
    "fastparquet",
]

[tool.setuptools.packages.find]
where = ["."]
